# Generated by Django 2.1.4 on 2018-12-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.BooleanField(default=False)),
                ('final_date', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_assist.Company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OfferRetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_assist.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_assist.Company')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thickness', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('cutting_length', models.IntegerField(blank=True, null=True)),
                ('cutting_time', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_assist.Company')),
                ('material',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_assist.Material')),
            ],
            options={
                'ordering': ['company', 'name', 'thickness'],
            },
        ),
        migrations.AddField(
            model_name='offerretail',
            name='retail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production_assist.Retail'),
        ),
        migrations.AddField(
            model_name='offer',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='production_assist.Person'),
        ),
        migrations.AddField(
            model_name='offer',
            name='retail',
            field=models.ManyToManyField(through='production_assist.OfferRetail', to='production_assist.Retail'),
        ),
    ]
