# Generated by Django 2.1.4 on 2019-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_assist', '0002_auto_20181231_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Registered'), (1, 'Project'), (2, 'Pricing'), (3, 'Production'), (4, 'Tooling'), (5, 'Ready to receive'), (6, 'Finished'), (7, 'On hold'), (8, 'Reclamation')], default=1),
        ),
    ]
