# Generated by Django 2.1.4 on 2019-01-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_assist', '0008_auto_20190108_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
