# Generated by Django 2.1.4 on 2019-01-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_assist', '0012_auto_20190110_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retail',
            options={'ordering': ['company', '-id', 'name', 'thickness']},
        ),
    ]
