# Generated by Django 2.1.5 on 2019-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_assist', '0015_auto_20190111_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Reclamation'), (0, 'Registered'), (1, 'Project'), (2, 'Pricing'), (3, 'Production'), (4, 'Tooling'), (5, 'Ready to receive'), (6, 'Finished'), (7, 'On hold')], default=0),
        ),
    ]
