# Generated by Django 2.1.4 on 2019-01-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_assist', '0017_auto_20190111_2003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offerretail',
            unique_together={('offer', 'retail')},
        ),
    ]
